### ISSUE TITLE
Task 2 (Mockups)

### ISSUE THREAD

**Issue by ala-n** [ibelous/inst-clone#2]
[-] (Critical) There is a filter selection but the date and author input fields are not displayed
[-] Also User should be able easily switch posts list between his posts and whole feed. 
[-] (Minor) It's better to draw another state for Guest instead of writting comments about multiple changes on the view. 
[-] (9-10) Tag input field behaviour isn't described 

[+] (0,5) An alternative view to see photo-posts larger a good idea

Current mark is 7-.

**Comment by ibelous** [comment]
fixed

**Comment by ala-n** [comment]
[-] Usability/cleanliness (field for date is simple text (from wireframes) etc.)
[-] simple tagfield (coma-separated tags is ok, but if you leave it as a simple field it should be described perfect)

Current mark is 8+.
